apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: subidev/client:main
        imagePullPolicy: Always
        command: ["/client"]
